export const RECHARGE_SERVICE_CODE = 'RECHARGE';
export const AADHAAR_SERVICE_CODE = 'AADHAAR';
export const PANCARD_SERVICE_CODE = 'PANCARD';
export const FUNDREQUEST_SERVICE_CODE = 'FUND_REQUEST';

export const RECHARGE_FEATURES = {
  INITIATE_RECHARGE: 'INITIATE_RECHARGE',
  FETCH_PLANS: 'FETCH_PLANS',
  FETCH_OFFERS: 'FETCH_OFFERS',
};

export const ROLE_HIERARCHY = {
  AZZUNIQUE: 'RESELLER',

  RESELLER: 'WHITE_LABEL',

  WHITE_LABEL: ['STATE_HEAD', 'MASTER_DISTRIBUTOR', 'DISTRIBUTOR', 'RETAILER'],

  STATE_HEAD: null,
  MASTER_DISTRIBUTOR: null,
  DISTRIBUTOR: null,
  RETAILER: null,
};
