export const PermissionsRegistryAdmin = {
  RECHARGE_SERVICE_PAGES_ADMIN_OPERATORS: {
    CREATE: 'RECHARGE.ADMIN.OPERATORS.CREATE',
    READ: 'RECHARGE.ADMIN.OPERATORS.READ',
    UPDATE: 'RECHARGE.ADMIN.OPERATORS.UPDATE',
    DELETE: 'RECHARGE.ADMIN.OPERATORS.DELETE',
  },

  RECHARGE_SERVICE_PAGES_ADMIN_CIRCLES: {
    CREATE: 'RECHARGE.ADMIN.CIRCLES.CREATE',
    READ: 'RECHARGE.ADMIN.CIRCLES.READ',
    UPDATE: 'RECHARGE.ADMIN.CIRCLES.UPDATE',
    DELETE: 'RECHARGE.ADMIN.CIRCLES.DELETE',
  },

  PLATFORM_SERVICES: {
    CREATE: 'PLATFORM.CREATE',
    UPDATE: 'PLATFORM.UPDATE',
    DELETE: 'PLATFORM.DELETE',
    ASSIGN_PROVIDER: 'PLATFORM.ASSIGN_PROVIDER',
    READ_ASSIGN_PROVIDER: 'PLATFORM.READ_ASSIGN_PROVIDER',
    UNASSIGN_PROVIDER: 'PLATFORM.UNASSIGN_PROVIDER',
  },

  PLATFORM_SERVICE_FEATURES: {
    CREATE: 'PLATFORM_FEATURE.CREATE',
    UPDATE: 'PLATFORM_FEATURE.UPDATE',
    DELETE: 'PLATFORM_FEATURE.DELETE',
  },

  PLATFORM_SERVICE_PROVIDERS: {
    READ: 'PLATFORM_SERVICE_PROVIDER.READ',
    CREATE: 'PLATFORM_SERVICE_PROVIDER.CREATE',
    UPDATE: 'PLATFORM_SERVICE_PROVIDER.UPDATE',
    DELETE: 'PLATFORM_SERVICE_PROVIDER.DELETE',
    VIEW_PROVIDER: 'PLATFORM_SERVICE_PROVIDER.VIEW_PROVIDER',
  },
};
