export const PermissionsRegistry = {
  USER: {
    CREATE: 'USER.CREATE',
    READ: 'USER.READ',
    UPDATE: 'USER.UPDATE',
    DELETE: 'USER.DELETE',
    ASSIGN_PERMISSIONS: 'USER.ASSIGN_PERMISSIONS',
    VIEW_DESCENDANTS: 'USER.VIEW_DESCENDANTS',
  },

  ROLE: {
    CREATE: 'ROLE.CREATE',
    READ: 'ROLE.READ',
    UPDATE: 'ROLE.UPDATE',
    DELETE: 'ROLE.DELETE',
    ASSIGN_PERMISSIONS: 'ROLE.ASSIGN_PERMISSIONS',
  },

  PERMISSION: {
    READ: 'PERMISSION.READ',
    ASSIGN: 'PERMISSION.ASSIGN',
  },

  DEPARTMENT: {
    CREATE: 'DEPARTMENT.CREATE',
    READ: 'DEPARTMENT.READ',
    UPDATE: 'DEPARTMENT.UPDATE',
    DELETE: 'DEPARTMENT.DELETE',
    ASSIGN_PERMISSIONS: 'DEPARTMENT.ASSIGN_PERMISSIONS',
  },

  EMPLOYEE: {
    CREATE: 'EMPLOYEE.CREATE',
    READ: 'EMPLOYEE.READ',
    UPDATE: 'EMPLOYEE.UPDATE',
    DELETE: 'EMPLOYEE.DELETE',
    CHANGE_STATUS: 'EMPLOYEE.CHANGE_STATUS',
    ASSIGN_PERMISSIONS: 'EMPLOYEE.ASSIGN_PERMISSIONS',
  },

  TENANT: {
    CREATE: 'TENANT.CREATE',
    READ: 'TENANT.READ',
    UPDATE: 'TENANT.UPDATE',
    DELETE: 'TENANT.DELETE',
    VIEW_DESCENDANTS: 'TENANT.VIEW_DESCENDANTS',
  },

  DOMAIN: {
    CREATE: 'DOMAIN.CREATE',
    READ: 'DOMAIN.READ',
    UPDATE: 'DOMAIN.UPDATE',
    DELETE: 'DOMAIN.DELETE',
  },

  COMMISSION: {
    READ: 'COMMISSION.READ',
    SET_RULE: 'COMMISSION.SET_RULE',
  },

  SERVER: {
    UPSERT: 'SERVER.UPSERT',
    READ: 'SERVER.READ',
  },

  SMTP: {
    CREATE: 'SMTP.CREATE',
    UPDATE: 'SMTP.UPDATE',
    READ: 'SMTP.READ',
  },

  AADHAAR_SERVICE_PAGES: {
    API_CREATE: 'AADHAAR.API_CREATE',
    MANUAL_CREATE: 'AADHAAR.MANUAL_CREATE',
    VERIFY: 'AADHAAR.VERIFY',
    UPDATE: 'AADHAAR.UPDATE',
    READ: 'AADHAAR.READ',
  },

  RECHARGE_SERVICE_PAGES: {
    CREATE: 'RECHARGE.CREATE',
    READ: 'RECHARGE.READ',
    UPDATE: 'RECHARGE.UPDATE',
    RETRY: 'RECHARGE.RETRY',
  },

  PLATFORM_SERVICES: {
    READ: 'PLATFORM.READ',
  },

  PLATFORM_SERVICE_FEATURES: {
    READ: 'PLATFORM_FEATURE.READ',
  },

  PLATFORM_SERVICE_TENANTS: {
    READ: 'PLATFORM_SERVICE_TENANT.READ',
    CREATE: 'PLATFORM_SERVICE_TENANT.CREATE',
    UPDATE: 'PLATFORM_SERVICE_TENANT.UPDATE',
    DELETE: 'PLATFORM_SERVICE_TENANT.DELETE',
  },
};
