import { PERMISSIONS } from "./permissionKeys";

export const PERMISSION_GROUPS = {
  MEMBER_MANAGEMENT: [PERMISSIONS.USER.READ, PERMISSIONS.ROLE.READ],
  EMPLOYEE_MANAGEMENT: [PERMISSIONS.EMPLOYEE.READ, PERMISSIONS.DEPARTMENT.READ],
  SETTINGS: [
    PERMISSIONS.SERVER.READ,
    PERMISSIONS.SMTP.READ,
    PERMISSIONS.DOMAIN.READ,
    PERMISSIONS.WEBSITE.READ,
    PERMISSIONS.SOCIAL_MEDIA.READ,
  ],
};
